### ISSUE TITLE
Please Help me

### ISSUE THREAD

**Issue by Sonytechbaku** [nikolaevich23/nikolaevich23.github.io#1]
Hello, I transferred your source codes to my site,

there was a problem

the installer is complete and the browser has disappeared.

Please help me.

![IMG_20200710_185524](https://user-images.githubusercontent.com/68062125/87168296-5226ee00-c2df-11ea-944b-c15bd5defe0c.jpg)

**Comment by nikolaevich23** [comment]
reinstal HFW 4.86.1
