### ISSUE TITLE
Не удалось подключиться к PSN в HEN 3.2.4

### ISSUE THREAD

**Issue by stam260782** [nikolaevich23/nikolaevich23.github.io#2]
Добавляемый в установке файл ps3-updatelist.txt выдает ошибку при попытке подключения к PSN, решается удалением, извините что пишу Я использую гугл переводчик.

**Comment by nikolaevich23** [comment]
ок, исправлено.

**Comment by stam260782** [comment]
Испанский язык

**Comment by nikolaevich23** [comment]
[Проверь это](https://github.com/nikolaevich23/nikolaevich23.github.io/raw/master/t/ps3hen_324-test.pkg) (dev_blind должен быть включен)

**Comment by stam260782** [comment]
Ошибка появляется при включении HEN и отключении системных вызовов и попытке подключения к PSN.

**Comment by nikolaevich23** [comment]
Не уловил. Какая ошибка? Пиши лучше в телеграмм (ссылка выше), так будет быстрее

**Comment by stam260782** [comment]
Я не владею русским, чтобы сделать через Telegram, ошибка пропадает при удалении файла с Hdd0

**Comment by nikolaevich23** [comment]
Про ps3-updatelist.txt я понял. Я удалил, но в тест не выкладывал (отдельный pkg). Пока занимаюсь переводом.

**Comment by nikolaevich23** [comment]
В релизе указанный файл удален.
